# Generated by Django 3.2 on 2021-04-17 15:02

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('state', models.CharField(choices=[('Resolved', 'RESOLVED'), ('To Validate', 'TO_VALIDATE'), ('Validated', 'VALIDATED')], default='to validate', max_length=100)),
                ('category', models.CharField(choices=[('Constructions', 'CONSTRUCTIONS'), ('Incident', 'INCIDENT'), ('Road Condition', 'ROAD_CONDITION'), ('Special Event', 'SPECIAL_EVENT'), ('Weather Condition', 'WEATHER_CONDITION')], default='incident', max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
