# Generated by Django 3.2 on 2021-04-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Constructions', 'CONSTRUCTIONS'), ('Incident', 'INCIDENT'), ('Road Condition', 'ROAD_CONDITION'), ('Special Event', 'SPECIAL_EVENT'), ('Weather Condition', 'WEATHER_CONDITION')], default='Incident', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('Resolved', 'RESOLVED'), ('To Validate', 'TO_VALIDATE'), ('Validated', 'VALIDATED')], default='To Validate', max_length=100),
        ),
    ]
